# Generated by Django 5.2 on 2025-04-14 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Listing Image', 'verbose_name_plural': 'Listing Images'},
        ),
        migrations.RemoveField(
            model_name='listingimage',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='listing',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, help_text='Contact phone number', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number (optional)', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('room', 'Room'), ('studio', 'Studio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listings/'),
        ),
    ]
