# Generated by Django 5.2 on 2025-10-21 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommateConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_requests', to=settings.AUTH_USER_MODEL)),
                ('roommate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='listings.roommateprofile')),
            ],
            options={
                'verbose_name': 'Roommate Connection',
                'verbose_name_plural': 'Roommate Connections',
                'ordering': ['-created_at'],
                'unique_together': {('requester', 'roommate_profile')},
            },
        ),
    ]
