# Generated by Django 5.2 on 2025-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_chatmessage_options_chatmessage_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='read',
            new_name='is_read',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
