# Generated by Django 5.2 on 2025-04-22 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_read_chatmessage_is_read_chatmessage_read_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RoommateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title for your roommate search', max_length=100)),
                ('age', models.PositiveIntegerField(help_text='Your age')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1)),
                ('city', models.CharField(max_length=50)),
                ('suburb', models.CharField(blank=True, max_length=50)),
                ('min_budget', models.DecimalField(decimal_places=2, help_text='Your minimum budget', max_digits=10)),
                ('max_budget', models.DecimalField(decimal_places=2, help_text='Your maximum budget', max_digits=10)),
                ('move_in_date', models.DateField(help_text='When are you looking to move in?')),
                ('lifestyle', models.CharField(blank=True, choices=[('early_bird', 'Early Bird'), ('night_owl', 'Night Owl'), ('social', 'Social/Outgoing'), ('quiet', 'Quiet/Private'), ('studious', 'Studious'), ('neat', 'Neat and Tidy'), ('relaxed', 'Relaxed about cleaning')], max_length=20)),
                ('bio', models.TextField(help_text='Tell potential roommates about yourself')),
                ('preferences', models.TextField(blank=True, help_text="Describe what you're looking for in a roommate or housing")),
                ('is_smoker', models.BooleanField(default=False)),
                ('has_pets', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
