# Generated by Django 5.2 on 2025-04-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_chatmessage_message_alter_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_direct_message',
            field=models.BooleanField(default=False, help_text='Flag for listings created for direct messaging only'),
        ),
    ]
