# Generated by Django 5.2 on 2025-05-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_savedsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('shared', 'Shared Room'), ('cottage', 'Cottage'), ('apartment', 'Apartment'), ('house', 'House')], max_length=100),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='property_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Room'), ('shared', 'Shared Room'), ('cottage', 'Cottage'), ('apartment', 'Apartment'), ('house', 'House')], max_length=100, null=True),
        ),
    ]
