# Generated by Django 5.2 on 2025-04-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_is_verified_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified_landlord',
            field=models.BooleanField(default=False, help_text='Indicates if the landlord has been verified'),
        ),
        migrations.CreateModel(
            name='LandlordVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Upload ID or proof of property ownership', upload_to='verification_documents/')),
                ('document_type', models.CharField(choices=[('id', 'Identification Document'), ('deed', 'Title Deed'), ('other', 'Other Proof of Ownership')], max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional information about your verification request')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on verification review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
