"""
Django settings for zim_rentals project.

Generated by 'django-admin startproject' using Django 4.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load environment variables from .env file
# THIS MUST BE CALLED EARLY, BEFORE ACCESSING os.getenv for these variables
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = str(os.getenv('DEBUG', 'False')).lower() == 'true' # Default to False if not set

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'debug_toolbar', # Conditionally added below
    
    # Local apps
    'accounts',
    'listings',
    'api',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware', # Conditionally added below
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Conditionally add Django Debug Toolbar
# if DEBUG:
#     INSTALLED_APPS.append('debug_toolbar')
#     MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware') # Insert at the beginning

ROOT_URLCONF = 'zim_rentals.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'listings.context_processors.unread_messages',
                'listings.context_processors.google_maps_api_key',
            ],
        },
    },
]

WSGI_APPLICATION = 'zim_rentals.wsgi.application'
ASGI_APPLICATION = 'zim_rentals.asgi.application' # Added for Daphne


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media' # We will let S3 handle this in production

# Storage Settings
# Default to FileSystemStorage. If not in DEBUG mode and S3 vars are set, use S3.
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
MEDIA_ROOT = BASE_DIR / 'media' # For local development

# AWS S3 settings for django-storages
# These will be overridden if USE_S3 is True (i.e., not in DEBUG mode and AWS_STORAGE_BUCKET_NAME is set)
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID') # Also used by SES, ensure it has S3 permissions
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY') # Also used by SES
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME') # e.g., 'us-east-1', 'eu-west-2'
AWS_S3_CUSTOM_DOMAIN = os.getenv('AWS_S3_CUSTOM_DOMAIN') # Default, or your CloudFront/custom domain
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400', # Cache static files for 1 day
}
AWS_LOCATION = 'media' # Optional: Subdirectory within your S3 bucket for media files
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'

# Determine if we should use S3 based on DEBUG and environment variables
USE_S3 = not DEBUG and AWS_STORAGE_BUCKET_NAME is not None

if USE_S3:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    # STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage' # Optional: if you want static files on S3 too
    # AWS_S3_STATIC_LOCATION = 'static' # If using S3 for static files
    # STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_S3_STATIC_LOCATION}/' # If using S3 for static files
    # No need to define MEDIA_ROOT when using S3 for default file storage as files are not stored locally
    if 'media' in MEDIA_ROOT.__str__(): # Check if MEDIA_ROOT was the default, to avoid error if it's already None
        MEDIA_ROOT = None # Files are not stored locally with S3
else:
    # Ensure MEDIA_ROOT is set for local development if not using S3
    if MEDIA_ROOT is None:
         MEDIA_ROOT = BASE_DIR / 'media'


STORAGES = {
    "default": {
        "BACKEND": DEFAULT_FILE_STORAGE, # Will be S3Boto3Storage in prod if configured
    },
    "staticfiles": {
        # Keep whitenoise for static files unless you explicitly want S3 for staticfiles too
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Django Allauth settings
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# Allauth settings
# ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # Deprecated
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
# ACCOUNT_EMAIL_REQUIRED = True  # Deprecated
# ACCOUNT_USERNAME_REQUIRED = True  # Deprecated
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_FORMS = {
    'login': 'accounts.forms.CustomLoginForm',
    'signup': 'accounts.forms.CustomSignupForm',
}
ACCOUNT_USERNAME_MIN_LENGTH = 3
ACCOUNT_PASSWORD_MIN_LENGTH = 8
ACCOUNT_USERNAME_BLACKLIST = ['admin', 'administrator', 'root', 'superuser']
ACCOUNT_EMAIL_SUBJECT_PREFIX = '[Home Marketplace] '
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https' # Ensure this is https for production
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/300s',  # 5 attempts per 5 minutes (replacing ACCOUNT_LOGIN_ATTEMPTS_LIMIT and TIMEOUT)
    'confirm_email': '1/180s',  # 1 attempt per 3 minutes (replacing ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN)
}
# ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 5  # Deprecated
# ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300  # 5 minutes - Deprecated
# ACCOUNT_EMAIL_CONFIRMATION_COOLDOWN = 180  # 3 minutes - Deprecated
ACCOUNT_PASSWORD_RESET_TIMEOUT = 86400  # 24 hours
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_EMAIL_CONFIRMATION_HMAC = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_PREVENT_ENUMERATION = True

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Email settings

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
EMAIL_PORT = os.environ.get('EMAIL_PORT')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL') # Must be a verified SES identity

# When using django-ses with SES API (Boto3), these are the primary settings from environment:
# EMAIL_BACKEND = os.getenv('EMAIL_BACKEND') # Should be 'django_ses.SESBackend'
# AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID') # For django-ses
# AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY') # For django-ses
# AWS_SES_REGION_NAME = os.getenv('AWS_SES_REGION_NAME') # For django-ses, e.g., 'eu-north-1'
# AWS_SES_AUTO_THROTTLE = float(os.getenv('AWS_SES_AUTO_THROTTLE', 0.5)) # Example, ensure it's a float

# The following are standard Django SMTP settings. 
# If EMAIL_BACKEND is 'django_ses.SESBackend', these are typically NOT used by django-ses for API calls.
# If you were to switch EMAIL_BACKEND to 'django.core.mail.backends.smtp.EmailBackend' 
# to use SES via SMTP, then you would configure these:
# EMAIL_HOST = os.getenv('EMAIL_HOST') # e.g., 'email-smtp.eu-north-1.amazonaws.com'
# EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
# EMAIL_USE_TLS = str(os.getenv('EMAIL_USE_TLS', 'True')).lower() == 'true'
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER') # SES SMTP username
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD') # SES SMTP password

# django-ses specific settings (optional, have defaults)
# AWS_SES_CONFIGSET = os.getenv('AWS_SES_CONFIGSET') # If you use SES Configuration Sets
# AWS_SES_RETURN_PATH = os.getenv('AWS_SES_RETURN_PATH') # If you need a custom return path

# Geoposition settings
GEOPOSITION_GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY')
GEOPOSITION_MAP_OPTIONS = {
    'minZoom': 3,
    'maxZoom': 15,
}
GEOPOSITION_MARKER_OPTIONS = {
    'cursor': 'move'
}

# Location Field Settings
LOCATION_FIELD = {
    'map.provider': 'google',
    'map.zoom': 13,
    'search.provider': 'google',
    'search.suffix': '',
    'provider.google.api': '//maps.googleapis.com/maps/api/js',
    'provider.google.api_key': os.getenv('GOOGLE_MAPS_API_KEY'),
    'provider.google.map_type': 'ROADMAP',
}

# New features
ENABLE_NOTIFICATIONS = True
ENABLE_CHAT = True
ENABLE_REVIEWS = True
ENABLE_FAVORITES = True
ENABLE_BOOKINGS = True

# Google Maps API Key - this is the one most likely used by your template context
# Ensure it's correctly passed to the template context if not via a default processor
GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY')

# Channels
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [],
        },
    },
}

# Chat settings
CHAT_MESSAGE_MAX_LENGTH = 1000

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# Celery Configuration Options
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Price Alerts Settings
PRICE_ALERTS_FREQUENCY = 24  # Hours between alert checks
PRICE_ALERTS_ENABLED = True

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
    },
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.AcceptHeaderVersioning',
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # For development - change in production
CORS_ALLOW_CREDENTIALS = True

# For production, specify allowed origins:
# CORS_ALLOWED_ORIGINS = [
#     "https://yourmobileapp.com",
# ]

# Debug Toolbar Settings
INTERNAL_IPS = [
    '127.0.0.1',
]

# Email settings for Contact Form
CONTACT_EMAIL_RECIPIENT = os.getenv('CONTACT_EMAIL_RECIPIENT', 'your_admin_email@example.com') # CHANGE THIS to your actual recipient

# Default contact details for display on the contact page
DEFAULT_CONTACT_EMAIL = os.getenv('DEFAULT_CONTACT_EMAIL')
DEFAULT_CONTACT_PHONE1 = os.getenv('DEFAULT_CONTACT_PHONE1')
DEFAULT_CONTACT_PHONE2 = os.getenv('DEFAULT_CONTACT_PHONE2', '') # Optional
DEFAULT_CONTACT_ADDRESS = os.getenv('DEFAULT_CONTACT_ADDRESS')
